# Cloud Build Configuration for Portfolio Website SSR Deployment
#
# Purpose: Automates the build and deployment process for the Next.js portfolio website
# to Google Cloud Run. This configuration defines a multi-step pipeline that:
# 1. Builds a Docker container image with the Next.js application
# 2. Pushes the image to Google Container Registry (GCR)
# 3. Deploys the container to Cloud Run with production configuration
#
# The build uses commit SHA for image tagging to enable version tracking and rollbacks.
# Cloud Run is configured with appropriate resource limits and scaling parameters
# for cost-effective operation while maintaining performance.

steps:
  # Step 1: Build the Docker container image
  # Tags the image with the commit SHA for version tracking
  # Firebase configuration should be passed via Secret Manager (not hardcoded)
  # For now, these are public client-side keys (safe to expose in client apps)
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/portfolio-website:$_COMMIT_SHA'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_API_KEY=${_FIREBASE_API_KEY}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=mindcruit.firebaseapp.com'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=mindcruit'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=mindcruit.firebasestorage.app'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=741046830246'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_APP_ID=1:741046830246:web:b6f39bac95c40d7511e067'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=G-TQD59X0NV5'
      - '--build-arg'
      - 'NEXT_PUBLIC_USE_FIREBASE_EMULATOR=false'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=https://us-central1-mindcruit.cloudfunctions.net'
      - '.'
  
  # Step 2: Push the container image to Google Container Registry
  # Makes the image available for Cloud Run deployment
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/portfolio-website:$_COMMIT_SHA']
  
  # Step 3: Deploy the container image to Cloud Run
  # Configures the service with production-ready settings
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'portfolio-website'
      - '--image=gcr.io/$PROJECT_ID/portfolio-website:$_COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--timeout=60s'
      - '--set-env-vars=NODE_ENV=production'

# Store the built image in Container Registry for future reference
images:
  - 'gcr.io/$PROJECT_ID/portfolio-website:$_COMMIT_SHA'

# Build timeout (20 minutes)
timeout: '1200s'

# Build options for performance optimization
options:
  # Use high-CPU machine for faster Docker builds
  machineType: 'N1_HIGHCPU_8'

# Substitutions for variables
substitutions:
  _COMMIT_SHA: 'latest'
  # Firebase API key - set this in Cloud Build trigger settings
  # Go to: Cloud Build > Triggers > Edit Trigger > Substitution variables
  # Add: _FIREBASE_API_KEY = [your-api-key]
  _FIREBASE_API_KEY: ''
